version: '3.3'

services:

  php:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: pastebin-fpm
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    networks:
      default:
        aliases:
          - fcgi

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: pastebin-nginx
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_webgateway
      traefik.backend: pastebin
      traefik.frontend.rule: "Host:pastebin.localhost"
      traefik.port: 8000
    links:
      - php
      - php:fcgi
    networks:
      - traefik_webgateway
      - default

  redis:
    image: redis:5.0-rc-alpine
    container_name: pastebin-redis
    read_only: true
    command: "redis-server --appendonly yes"
    networks:
      default:
        aliases:
          - redis
    expose:
      - "6379"
    tmpfs:
      - /tmp
    volumes:
      - "pastebin-redisdata:/data"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    sysctls:
      net.core.somaxconn: 1024

networks:

  default:

  traefik_webgateway:
    external: true

volumes:

  pastebin-redisdata:
