paste.index:
  path: /
  methods: [GET]
  defaults: { _controller: paste.controller.index }

paste.create:
  path: /
  methods: [PUT,POST]
  defaults: { _controller: paste.controller.create }

paste.read:
  path: /{id}
  methods: [GET]
  defaults: { _controller: paste.controller.read }

paste.read.raw:
  path: /{id}/raw
  methods: [GET]
  defaults: { _controller: paste.controller.read, raw: true }

paste.update:
  path: /{id}
  methods: [PUT]
  defaults: { _controller: paste.controller.update }

paste.delete:
  path: /{id}
  methods: [DELETE]
  defaults: { _controller: paste.controller.delete }
