name: Continuous Integration

on: ['push']

jobs:

  phpstan:

    name: PHPStan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: vendor-${{ hashFiles('composer.lock') }}
    - if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: make install
    - run: make phpstan

  phpunit:

    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: vendor-${{ hashFiles('composer.lock') }}
    - if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: make install
    - run: make phpunit
    - run: make phpstan
    - run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
